using System;
using System.Collections.Generic;
using System.Reflection;
using UnityEngine;

public partial class GameManager
{
    GameObject moonSlashExplode,
        magicLaserImpact,
        slaughterProjectile,
        slaughterExplosion,
        strongDudePunchImpact,
        samuraiSlash,
        bladeOfPhongTornadoImpact,
        bladeOfVuImpact,
        arrow,
        elementalLeafRangerArrow,
        elementalLeafRangerPoisonArrowImpact,
        elementalLeafRangerVineArrowImpact,
        wanderMagicianProjectile,
        vanishEffect,
        bladeOfMinhKhaiSlashEffect,
        bladeOfPhongTornadoEffect,
        ghost,
        bladeOfVuStar,
        bladeOfVuSlash,
        pierceStrike,
        pierceStrikeSecondPhase,
        deepBladeSlash,
        rayOfJungleBeam,
        woodCryArrow,
        elementalLeafRangerPoisonArrow,
        elementalLeafRangerVineArrow,
        lightingForwardLighting,
        blueHole,
        nuclearBombExplosion,
        swordTempestSlash1,
        swordTempestSlash2,
        swordTempestSlash3,
        dashEffect,
        dashExplode,
        magicLaser,
        moonSlash,
        scatterArrow,
        scatterCharge,
        attackCollider,
        dieDissolve,
        strongDudeShockwave,
        knockUpCollider,
        pushRandomCollider,
        pushCollider,
        stunCollider,
        phantomPulseDragon,
        infernalTideFlame,
        infernalTideFlameNoReceiver,
        infernalTideFan,
        scatterFlash,
        stormFangMergeBlades,
        stormFangMergeProgress,
        kunai,
        kunaiHit,
        arcaneSwarmSlash1,
        arcaneSwarmSlash2,
        arcaneSwarmSlash3,
        arcaneSwarmSlash4,
        arcaneSwarmSlash5,
        orbitalNemesisDash,
        heliosGazeRay,
        rimuruCombo1SlashA,
        rimuruCombo1SlashB,
        rimuruCombo1Dash,
        rimuruCombo1DashImpact,
        rimuruCombo2SlashA,
        rimuruCombo2SlashB,
        sovereignFlowEffect,
        rimuruFireBall,
        rimuruFireBallImpact,
        rimuruLightingWolf,
        rimuruLightingWolfSummonCircle,
        rimuruHeavenFallRay,
        virgilAttackImpact,
        virgilAttackSlash,
        rimuruCombo1SlashAWithCollider,
        dimmingEdgeEffect,
        ironCladVFX;

    List<string> prefabNames = new()
    {
        "moonSlashExplode",
        "magicLaserImpact",
        "slaughterProjectile",
        "slaughterExplosion",
        "strongDudePunchImpact",
        "samuraiSlash",
        "bladeOfPhongTornadoImpact",
        "bladeOfVuImpact",
        "arrow",
        "elementalLeafRangerArrow",
        "elementalLeafRangerPoisonArrowImpact",
        "elementalLeafRangerVineArrowImpact",
        "wanderMagicianProjectile",
        "vanishEffect",
        "bladeOfMinhKhaiSlashEffect",
        "bladeOfPhongTornadoEffect",
        "ghost",
        "bladeOfVuStar",
        "bladeOfVuSlash",
        "pierceStrike",
        "pierceStrikeSecondPhase",
        "deepBladeSlash",
        "rayOfJungleBeam",
        "woodCryArrow",
        "elementalLeafRangerPoisonArrow",
        "elementalLeafRangerVineArrow",
        "lightingForwardLighting",
        "blueHole",
        "nuclearBombExplosion",
        "swordTempestSlash1",
        "swordTempestSlash2",
        "swordTempestSlash3",
        "dashEffect",
        "dashExplode",
        "magicLaser",
        "moonSlash",
        "scatterArrow",
        "scatterCharge",
        "attackCollider",
        "dieDissolve",
        "strongDudeShockwave",
        "knockUpCollider",
        "pushRandomCollider",
        "pushCollider",
        "stunCollider",
        "phantomPulseDragon",
        "infernalTideFlame",
        "infernalTideFlameNoReceiver",
        "infernalTideFan",
        "scatterFlash",
        "stormFangMergeBlades",
        "stormFangMergeProgress",
        "kunai",
        "kunaiHit",
        "arcaneSwarmSlash1",
        "arcaneSwarmSlash2",
        "arcaneSwarmSlash3",
        "arcaneSwarmSlash4",
        "arcaneSwarmSlash5",
        "orbitalNemesisDash",
        "heliosGazeRay",
        "rimuruCombo1SlashA",
        "rimuruCombo1SlashB",
        "rimuruCombo1Dash",
        "rimuruCombo1DashImpact",
        "rimuruCombo2SlashA",
        "rimuruCombo2SlashB",
        "sovereignFlowEffect",
        "rimuruFireBall",
        "rimuruFireBallImpact",
        "rimuruLightingWolf",
        "rimuruLightingWolfSummonCircle",
        "rimuruHeavenFallRay",
        "virgilAttackImpact",
        "virgilAttackSlash",
        "rimuruCombo1SlashAWithCollider",
        "dimmingEdgeEffect",
        "ironCladVFX",
    };

    void LoadGameEffectPrefabs()
    {
        Type type = GetType();
        foreach (var name in prefabNames)
        {
            FieldInfo field = type.GetField(
                name,
                BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic
            );
            field.SetValue(this, Resources.Load<GameObject>(CapitalizeFirstLetter(name)));
        }
    }

    string CapitalizeFirstLetter(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;
        return char.ToUpper(input[0]) + input.Substring(1);
    }
}
