using System;
using System.Collections.Generic;
using System.Reflection;
using UnityEngine;

public partial class GameManager
{
    GameObject itemPF,
        championRewardPF,
        relicPF,
        gold;
    GameObject magicLaserImpact,
        slaughterProjectile,
        slaughterExplosion,
        strongDudePunchImpact,
        samuraiSlash,
        bladeOfPhongTornadoImpact,
        defaultImpactEffect,
        arrow,
        elementalLeafRangerArrow,
        elementalLeafRangerPoisonArrowImpact,
        wanderMagicianProjectile,
        vanishEffect,
        bladeOfPhongTornadoEffect,
        ghost,
        pierceStrike,
        pierceStrikeSecondPhase,
        deepBladeSlash,
        rayOfJungleBeam,
        elementalLeafRangerPoisonArrow,
        swordTempestSlash1,
        swordTempestSlash2,
        swordTempestSlash3,
        dashEffect,
        dashExplode,
        magicLaser,
        scatterArrow,
        scatterCharge,
        attackCollider,
        dieDissolve,
        strongDudeShockwave,
        knockUpCollider,
        pushRandomCollider,
        pushCollider,
        stunCollider,
        phantomPulseDragon,
        infernalTideFlame,
        infernalTideFlameNoReceiver,
        infernalTideFan,
        scatterFlash,
        rimuruCombo1SlashA,
        rimuruCombo1SlashB,
        rimuruCombo1Dash,
        rimuruCombo1DashImpact,
        virgilAttackImpact,
        virgilAttackSlash,
        rimuruCombo1SlashAWithCollider,
        dimmingEdgeEffect,
        ironCladVFX,
        zukoAttack1Impact,
        zukoAttack2Slash,
        zukoAttack2Impact,
        zukoAttack3Slash,
        zukoAttack3Impact,
        zukoAttack4Slash,
        zukoAttack4Impact,
        forceBreakerFirstPunch,
        forceBreakerKick,
        forceBreakerProjectile,
        forceBreakerProjectileImpact,
        forceBreakerPunchImpact,
        forceBreakerSecondPunch,
        forceBreakerWave,
        pitSlash1,
        pitSlash2,
        pitSlash3,
        pitSlash4,
        pitSlashImpact,
        pitSpin,
        coleAttack1Slash,
        coleAttack1Impact,
        coleAttackImpact,
        bloodOfTheFallenCast,
        bloodOfTheFallenEnergy,
        novaKadeBullet,
        novaKadeBulletHit,
        novaKadeGrenade,
        novaKadeGrenadeExplosion,
        aquaenAttack1Impact,
        twinsOfCataclysmEffect,
        glacistreamEffect,
        raikenDart,
        jinseiKunai,
        eyeOfTheReaperEffect,
        rubyRoseProjectile,
        gooRushSmoke,
        mukaiRock,
        mukaiPillar,
        championTeleportEffect,
        enemyShowupEffect,
        wanderMagicianHealEffect,
        moonCleaverImpact;

    List<string> prefabNames = new()
    {
        "magicLaserImpact",
        "slaughterProjectile",
        "slaughterExplosion",
        "strongDudePunchImpact",
        "samuraiSlash",
        "bladeOfPhongTornadoImpact",
        "defaultImpactEffect",
        "arrow",
        "elementalLeafRangerArrow",
        "elementalLeafRangerPoisonArrowImpact",
        "wanderMagicianProjectile",
        "vanishEffect",
        "bladeOfPhongTornadoEffect",
        "ghost",
        "pierceStrike",
        "pierceStrikeSecondPhase",
        "deepBladeSlash",
        "rayOfJungleBeam",
        "elementalLeafRangerPoisonArrow",
        "swordTempestSlash1",
        "swordTempestSlash2",
        "swordTempestSlash3",
        "dashEffect",
        "dashExplode",
        "magicLaser",
        "scatterArrow",
        "scatterCharge",
        "attackCollider",
        "dieDissolve",
        "strongDudeShockwave",
        "knockUpCollider",
        "pushRandomCollider",
        "pushCollider",
        "stunCollider",
        "phantomPulseDragon",
        "infernalTideFlame",
        "infernalTideFlameNoReceiver",
        "infernalTideFan",
        "scatterFlash",
        "rimuruCombo1SlashA",
        "rimuruCombo1SlashB",
        "rimuruCombo1Dash",
        "rimuruCombo1DashImpact",
        "virgilAttackImpact",
        "virgilAttackSlash",
        "rimuruCombo1SlashAWithCollider",
        "dimmingEdgeEffect",
        "ironCladVFX",
        "zukoAttack1Impact",
        "zukoAttack2Slash",
        "zukoAttack2Impact",
        "zukoAttack3Slash",
        "zukoAttack3Impact",
        "zukoAttack4Slash",
        "zukoAttack4Impact",
        "forceBreakerFirstPunch",
        "forceBreakerKick",
        "forceBreakerProjectile",
        "forceBreakerProjectileImpact",
        "forceBreakerPunchImpact",
        "forceBreakerSecondPunch",
        "forceBreakerWave",
        "pitSlash1",
        "pitSlash2",
        "pitSlash3",
        "pitSlash4",
        "pitSlashImpact",
        "pitSpin",
        "coleAttack1Slash",
        "coleAttack1Impact",
        "coleAttackImpact",
        "bloodOfTheFallenCast",
        "bloodOfTheFallenEnergy",
        "novaKadeBullet",
        "novaKadeBulletHit",
        "novaKadeGrenade",
        "novaKadeGrenadeExplosion",
        "aquaenAttack1Impact",
        "twinsOfCataclysmEffect",
        "glacistreamEffect",
        "raikenDart",
        "jinseiKunai",
        "eyeOfTheReaperEffect",
        "rubyRoseProjectile",
        "gooRushSmoke",
        "mukaiRock",
        "mukaiPillar",
        "championTeleportEffect",
        "enemyShowupEffect",
        "wanderMagicianHealEffect",
        "moonCleaverImpact",
    };

    void LoadGameEffectPrefabs()
    {
        Type type = GetType();
        foreach (var name in prefabNames)
        {
            FieldInfo field = type.GetField(
                name,
                BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic
            );
            field.SetValue(this, Resources.Load<GameObject>(CapitalizeFirstLetter(name)));
        }
    }

    string CapitalizeFirstLetter(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;
        return char.ToUpper(input[0]) + input.Substring(1);
    }
}
