using System;
using System.Collections.Generic;
using System.Reflection;
using UnityEngine;

public partial class GameManager
{
    public ObjectPool itemPool,
        championRewardUIPool,
        relicPool,
        goldPool;
    public ObjectPool magicLaserImpactPool,
        slaughterProjectilePool,
        slaughterExplosionPool,
        strongDudePunchImpactPool,
        samuraiSlashPool,
        bladeOfPhongTornadoImpactPool,
        defaultImpactEffectPool,
        arrowPool,
        elementalLeafRangerArrowPool,
        wanderMagicianProjectilePool,
        vanishEffectPool,
        bladeOfPhongTornadoEffectPool,
        ghostPool,
        pierceStrikePool,
        pierceStrikeSecondPhasePool,
        deepBladeSlashPool,
        rayOfJungleBeamPool,
        swordTempestSlash1Pool,
        swordTempestSlash2Pool,
        swordTempestSlash3Pool,
        dashEffectPool,
        dashExplodePool,
        magicLaserPool,
        scatterArrowPool,
        scatterChargePool,
        attackColliderPool,
        dieDissolvePool,
        strongDudeShockwavePool,
        knockUpColliderPool,
        pushRandomColliderPool,
        pushColliderPool,
        stunColliderPool,
        phantomPulseDragonPool,
        infernalTideFlamePool,
        infernalTideFlameNoReceiverPool,
        infernalTideFanPool,
        scatterFlashPool,
        rimuruCombo1SlashAPool,
        rimuruCombo1SlashBPool,
        rimuruCombo1DashPool,
        rimuruCombo1DashImpactPool,
        virgilAttackImpactPool,
        virgilAttackSlashPool,
        rimuruCombo1SlashAWithColliderPool,
        dimmingEdgeEffectPool,
        ironCladVFXPool,
        zukoAttack1ImpactPool,
        zukoAttack2SlashPool,
        zukoAttack2ImpactPool,
        zukoAttack3SlashPool,
        zukoAttack3ImpactPool,
        zukoAttack4SlashPool,
        zukoAttack4ImpactPool,
        forceBreakerFirstPunchPool,
        forceBreakerKickPool,
        forceBreakerProjectilePool,
        forceBreakerProjectileImpactPool,
        forceBreakerPunchImpactPool,
        forceBreakerSecondPunchPool,
        forceBreakerWavePool,
        pitSlash1Pool,
        pitSlash2Pool,
        pitSlash3Pool,
        pitSlash4Pool,
        pitSlashImpactPool,
        pitSpinPool,
        coleAttack1SlashPool,
        coleAttack1ImpactPool,
        coleAttackImpactPool,
        bloodOfTheFallenCastPool,
        bloodOfTheFallenEnergyPool,
        novaKadeBulletPool,
        novaKadeBulletHitPool,
        novaKadeGrenadePool,
        novaKadeGrenadeExplosionPool,
        aquaenAttack1ImpactPool,
        twinsOfCataclysmEffectPool,
        glacistreamEffectPool,
        raikenDartPool,
        jinseiKunaiPool,
        eyeOfTheReaperEffectPool,
        rubyRoseProjectilePool,
        gooRushSmokePool,
        mukaiRockPool,
        mukaiPillarPool,
        championTeleportEffectPool,
        enemyShowupEffectPool,
        wanderMagicianHealEffectPool,
        moonCleaverImpactPool;
    List<string> objectPoolNames = new()
    {
        "magicLaserImpactPool",
        "slaughterProjectilePool",
        "slaughterExplosionPool",
        "strongDudePunchImpactPool",
        "samuraiSlashPool",
        "bladeOfPhongTornadoImpactPool",
        "defaultImpactEffectPool",
        "arrowPool",
        "elementalLeafRangerArrowPool",
        "wanderMagicianProjectilePool",
        "vanishEffectPool",
        "bladeOfPhongTornadoEffectPool",
        "ghostPool",
        "pierceStrikePool",
        "pierceStrikeSecondPhasePool",
        "deepBladeSlashPool",
        "rayOfJungleBeamPool",
        "swordTempestSlash1Pool",
        "swordTempestSlash2Pool",
        "swordTempestSlash3Pool",
        "dashEffectPool",
        "dashExplodePool",
        "magicLaserPool",
        "scatterArrowPool",
        "scatterChargePool",
        "attackColliderPool",
        "dieDissolvePool",
        "strongDudeShockwavePool",
        "knockUpColliderPool",
        "pushRandomColliderPool",
        "pushColliderPool",
        "stunColliderPool",
        "phantomPulseDragonPool",
        "infernalTideFlamePool",
        "infernalTideFlameNoReceiverPool",
        "infernalTideFanPool",
        "scatterFlashPool",
        "rimuruCombo1SlashAPool",
        "rimuruCombo1SlashBPool",
        "rimuruCombo1DashPool",
        "rimuruCombo1DashImpactPool",
        "virgilAttackImpactPool",
        "virgilAttackSlashPool",
        "rimuruCombo1SlashAWithColliderPool",
        "dimmingEdgeEffectPool",
        "ironCladVFXPool",
        "zukoAttack1ImpactPool",
        "zukoAttack2SlashPool",
        "zukoAttack2ImpactPool",
        "zukoAttack3SlashPool",
        "zukoAttack3ImpactPool",
        "zukoAttack4SlashPool",
        "zukoAttack4ImpactPool",
        "forceBreakerFirstPunchPool",
        "forceBreakerKickPool",
        "forceBreakerProjectilePool",
        "forceBreakerProjectileImpactPool",
        "forceBreakerPunchImpactPool",
        "forceBreakerSecondPunchPool",
        "forceBreakerWavePool",
        "pitSlash1Pool",
        "pitSlash2Pool",
        "pitSlash3Pool",
        "pitSlash4Pool",
        "pitSlashImpactPool",
        "pitSpinPool",
        "coleAttack1SlashPool",
        "coleAttack1ImpactPool",
        "coleAttackImpactPool",
        "bloodOfTheFallenCastPool",
        "bloodOfTheFallenEnergyPool",
        "novaKadeBulletPool",
        "novaKadeBulletHitPool",
        "novaKadeGrenadePool",
        "novaKadeGrenadeExplosionPool",
        "aquaenAttack1ImpactPool",
        "twinsOfCataclysmEffectPool",
        "glacistreamEffectPool",
        "raikenDartPool",
        "jinseiKunaiPool",
        "eyeOfTheReaperEffectPool",
        "rubyRoseProjectilePool",
        "gooRushSmokePool",
        "mukaiRockPool",
        "mukaiPillarPool",
        "championTeleportEffectPool",
        "enemyShowupEffectPool",
        "wanderMagicianHealEffectPool",
        "moonCleaverImpactPool",
    };

    void InitAllEffectPools()
    {
        LoadGameEffectPrefabs();
        Type type = GetType();
        foreach (var name in objectPoolNames)
        {
            FieldInfo field = type.GetField(
                name,
                BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic
            );

            /* Create pools from prefabs */
            var t_prefab =
                type.GetField(
                        name[..^4],
                        BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic
                    )
                    .GetValue(this) as GameObject;
            field.SetValue(
                this,
                new ObjectPool(
                    t_prefab,
                    new PoolArgument(ComponentType.GameEffect, PoolArgument.WhereComponent.Self)
                )
            );

            /* Link Pools with ScriptableObjects */
            poolLink.Add(
                t_prefab.GetComponent<GameEffect>().gameEffectSO,
                (ObjectPool)field.GetValue(this)
            );
        }
    }
}
